# coding: utf-8
from sqlalchemy import Column, Index, String, text
from sqlalchemy.dialects.mysql import INTEGER, SMALLINT
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()
metadata = Base.metadata


class UrlRewrite(Base):
    __tablename__ = 'url_rewrite'
    __table_args__ = (
        Index('URL_REWRITE_REQUEST_PATH_STORE_ID', 'request_path', 'store_id', unique=True),
        Index('URL_REWRITE_STORE_ID_ENTITY_ID', 'store_id', 'entity_id'),
        {'comment': 'Url Rewrites'}
    )

    url_rewrite_id = Column(INTEGER(10), primary_key=True, comment='Rewrite ID')
    entity_type = Column(String(32), nullable=False, comment='Entity type code')
    entity_id = Column(INTEGER(10), nullable=False, index=True, comment='Entity ID')
    request_path = Column(String(255), comment='Request Path')
    target_path = Column(String(255), index=True, comment='Target Path')
    redirect_type = Column(SMALLINT(5), nullable=False, server_default=text("0"), comment='Redirect Type')
    store_id = Column(SMALLINT(5), nullable=False, comment='Store ID')
    description = Column(String(255), comment='Description')
    is_autogenerated = Column(SMALLINT(5), nullable=False, server_default=text("0"), comment='Is rewrite generated automatically flag')
    metadata_ = Column('metadata', String(255), comment='Meta data for url rewrite')
